-- 宏浩英语学习网页：Supabase 数据表与访问权限
-- 在 Supabase Dashboard 的 SQL Editor 中完整运行一次即可。

create table if not exists public.student_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_key text not null,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, course_key)
);

create table if not exists public.vocabulary (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  status text not null default 'unknown' check (status in ('unknown', 'uncertain')),
  source text not null default 'manual',
  meaning text not null default '',
  part_of_speech text not null default '',
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  unique (user_id, word)
);

alter table public.student_progress enable row level security;
alter table public.vocabulary enable row level security;

drop policy if exists "student reads own progress" on public.student_progress;
drop policy if exists "student inserts own progress" on public.student_progress;
drop policy if exists "student updates own progress" on public.student_progress;
drop policy if exists "student deletes own progress" on public.student_progress;

create policy "student reads own progress"
on public.student_progress for select
using (auth.uid() = user_id);

create policy "student inserts own progress"
on public.student_progress for insert
with check (auth.uid() = user_id);

create policy "student updates own progress"
on public.student_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "student deletes own progress"
on public.student_progress for delete
using (auth.uid() = user_id);

drop policy if exists "student reads own vocabulary" on public.vocabulary;
drop policy if exists "student inserts own vocabulary" on public.vocabulary;
drop policy if exists "student updates own vocabulary" on public.vocabulary;
drop policy if exists "student deletes own vocabulary" on public.vocabulary;

create policy "student reads own vocabulary"
on public.vocabulary for select
using (auth.uid() = user_id);

create policy "student inserts own vocabulary"
on public.vocabulary for insert
with check (auth.uid() = user_id);

create policy "student updates own vocabulary"
on public.vocabulary for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "student deletes own vocabulary"
on public.vocabulary for delete
using (auth.uid() = user_id);

grant select, insert, update, delete on public.student_progress to authenticated;
grant select, insert, update, delete on public.vocabulary to authenticated;
grant usage, select on sequence public.student_progress_id_seq to authenticated;
grant usage, select on sequence public.vocabulary_id_seq to authenticated;
